### ISSUE TITLE
V9 compatibility with Template Wall Collision module

### ISSUE THREAD

**Issue by ravingdragoon** [kandashi/Active-Auras#201]
**Describe the bug**
I know that AA is not V9 compatible yet, but I wanted you to be aware of the conflict with Template Wall Collision.

**To Reproduce**
1. Install both modules and their dependencies in Foundry V9
2. Activate both modules and their dependencies.
3. See error in the Dev Console

**Expected behavior**
No Error

**Screenshots**
```
aura.js:176 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'id')
    at Function.UpdateToken (aura.js:176)
    at Function.UpdateAllTokens (aura.js:112)
    at Function.MainAura (aura.js:43)
    at CollateAuras (collateAuras.js:64)
UpdateToken	@	aura.js:176
UpdateAllTokens	@	aura.js:112
MainAura	@	aura.js:43
CollateAuras	@	collateAuras.js:64
await in CollateAuras (async)		
CollateAuras	@	collateAuras.js:64
await in CollateAuras (async)		
(anonymous)	@	AAhooks.js:21
_call	@	foundry.js:294
callAll	@	foundry.js:253
setupGame	@	foundry.js:5503
```

**Environment:**
 - OS: Window 10
 - Browser: Chrome
 - Foundry Version: V9
 - Module Version: 0.3.08
 - All Modules Disabled: Yes, except Find the Culprit

**Comment by kandashi** [comment]
Thats nothing to do with that module and is just a v9 bug fixed in the latest branch

**Comment by ravingdragoon** [comment]
What latest branch? I just tried your V9 branch, and I still get the error if I have Template Wall Collision enabled, but I do not receive the error if it is disabled.
