### ISSUE TITLE
[SUGGESTION] Checkbox to disable aura if token is hidden

### ISSUE THREAD

**Issue by JJBocanegra** [kandashi/Active-Auras#30]
I have the habit of having the enemies hidden in the map that are exploring the characters and make them visible when they enter in action, but when this happens and the characters pass near an invisible token, the aura applies them immediately and they realize that there is something strange. It is especially clear when used together with Token Magic FX.

If at the time of setting up the aura there was a checkbox to allow this case, it would be very helpful.

**Comment by kandashi** [comment]
That should be possible yes

**Comment by kandashi** [comment]
closed in 0.1.2

**Comment by JJBocanegra** [comment]
I tried it and it's working except for one little detail.

If I have the aura applying to a nearby token and hide, the aura is still present on that nearby token, but if I reveal the source aura token again, that's when the aura dissapear.

This GIF will clarify it, basically the hidden effect toggles everytime the source token is visible.

![active-aura](https://user-images.githubusercontent.com/5797636/104574791-bcd23100-5656-11eb-91e3-1eb003ecec5f.gif)

**Comment by kandashi** [comment]
Are you on 0.1.2 or 0.1 21, the latest version should have fixed this...

**Comment by JJBocanegra** [comment]
I'm on 0.1.21

**Comment by kandashi** [comment]
I'll look onto it

**Comment by kandashi** [comment]
I cant seem to replicate this. would you mind sending over the actor with the effect?

**Comment by JJBocanegra** [comment]
Here it is, I tried it in a new empty world without modules and the problem is a bit different, it's just like before, when hidden the aura is not disabled.

[fvtt-Actor-Cuchilla_nocturna_[Night_Blade].zip](https://github.com/kandashi/Active-Auras/files/5814829/fvtt-Actor-Cuchilla_nocturna_.Night_Blade.zip)

**Comment by JJBocanegra** [comment]
> ![active-aura](https://user-images.githubusercontent.com/5797636/104574791-bcd23100-5656-11eb-91e3-1eb003ecec5f.gif)

This is still happening in v0.1.23 😢

**Comment by kandashi** [comment]
If you are free in 4-5 hours can I join your game and test?

**Comment by JJBocanegra** [comment]
I can't later, I'm from Spain, I can do it now if you need or tomorrow at any hour ;)

**Comment by kandashi** [comment]
Im free tomorrow until 2pm gmt

**Comment by JJBocanegra** [comment]
Perfect, I will leave it open when I wake up ;)

**Comment by JJBocanegra** [comment]
It's on

**Comment by kandashi** [comment]
Fixed in #1.2.6

**Comment by JJBocanegra** [comment]
I'm having this same problem again with 0.1.32 and the "ignore self" doesn't work.
![active-auras](https://user-images.githubusercontent.com/5797636/105576255-d9b2e680-5d71-11eb-8504-cf503f2652f8.gif)


I created a world for you to test it, it uses this modules
![image](https://user-images.githubusercontent.com/5797636/105576264-ef281080-5d71-11eb-85f3-dad7584cf643.png)

**Here is the world to download:**
[active-auras-bug-world.zip](https://github.com/kandashi/Active-Auras/files/5860051/active-auras-bug.zip)

**Comment by kandashi** [comment]
So, to make the aura no apply to the owning actor you will need to re-make the aura. There was a little bug in there too which I have now fixed (the no aura application when first moving into the aura)

**Comment by JJBocanegra** [comment]
I remade it removing the entire effect and creating it again and it still have these problems, I noticed even moving around a player token activate or deactivate the effect.

![active-auras](https://user-images.githubusercontent.com/5797636/105628966-7b086e00-5e40-11eb-8922-fd4deed135c8.gif)

**Comment by kandashi** [comment]
when you are free tomorrow, send me a message an i'll join your world again to test

**Comment by JJBocanegra** [comment]
I created an isolated world to test. The active modules are:
![image](https://user-images.githubusercontent.com/5797636/105689397-ff1f2c00-5efa-11eb-8e16-ae33fd0d9c7b.png)

Here is the zip of the world:
[pruebas.zip](https://github.com/kandashi/Active-Auras/files/5865599/pruebas.zip)

The problem from the previous comment was now nowhere to be seen as for the new update :) but now the aura of a hidden token seems to be applying like before:
![active-auras](https://user-images.githubusercontent.com/5797636/105689360-f2023d00-5efa-11eb-88df-e7f2b5ca1ca4.gif)


I will leave that test world open if you need it on my machine:
https://foundry-rol.ddns.net:30000/join

**Comment by kandashi** [comment]
This should be fixed now in #55

**Comment by JJBocanegra** [comment]
It seems to work perfectly :)

Thanks a lot kandashi!
